# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.provision "shell", inline: "apt-get update && apt-get install -y docker.io"
  end
end
